application: gae-examples
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# API exposed through Endpoints
- url: /_ah/spi/.*
  script: endpoints.service.app

# main webapp handlers
- url: .*
  script: main.app
#- url: /channel
  #script: /channel/handlers.py

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"

# For channel to handle connect/disconnect events
inbound_services:
- channel_presence